## Design model to predict credit card risk data using multi-layer perceptron. Display weights in each layer.

In [6]:
import numpy as np
# 1. Generate Synthetic Credit Card Risk Data
def generate_data(n_samples=1000):
    np.random.seed(42)
    X = np.random.rand(n_samples, 3)  # 3 features (e.g., income, age, loan amount)
    # Target (0 = low risk, 1 = high risk)
    Y = (X[:, 0] + X[:, 1] - X[:, 2] > 1).astype(int).reshape(-1, 1)
    return X, Y
# 2. Initialize the parameters for the MLP
def initialize_parameters(layer_sizes):
    parameters = {}
    parameters['W1'] = np.random.randn(layer_sizes[0], layer_sizes[1]) * 0.01
    parameters['b1'] = np.zeros((1, layer_sizes[1]))
    parameters['W2'] = np.random.randn(layer_sizes[1], layer_sizes[2]) * 0.01
    parameters['b2'] = np.zeros((1, layer_sizes[2]))
    parameters['W3'] = np.random.randn(layer_sizes[2], layer_sizes[3]) * 0.01
    parameters['b3'] = np.zeros((1, layer_sizes[3]))
    return parameters
# 3. Forward pass
def forward(X, parameters):
    cache = {}
    A = X
    cache['A0'] = A
    L = len(parameters) // 2  # Number of layers
    for l in range(1, L+1):
        Z = np.dot(A, parameters['W' + str(l)]) + parameters['b' + str(l)]
        A = np.maximum(0, Z)  # ReLU activation
        cache['A' + str(l)] = A
        cache['Z' + str(l)] = Z

    return A, cache
# 4. Compute loss (Binary Cross-Entropy)
def compute_loss(Y, A):
    m = Y.shape[0]
    loss = -np.mean(Y * np.log(A + 1e-8) + (1 - Y) * np.log(1 - A + 1e-8))
    return loss
# 5. Backward pass
def backward(X, Y, parameters, cache):
    gradients = {}
    L = len(parameters) // 2  # Number of layers
    m = X.shape[0]
    # Gradient of output layer
    dA = -(Y / (cache['A' + str(L)] + 1e-8)) + (1 - Y) / (1 - cache['A' + str(L)] + 1e-8)
    dZ = dA * (cache['Z' + str(L)] > 0)  # ReLU derivative
    gradients['dW' + str(L)] = np.dot(cache['A' + str(L-1)].T, dZ) / m
    gradients['db' + str(L)] = np.sum(dZ, axis=0, keepdims=True) / m
    for l in reversed(range(1, L)):
        dA = np.dot(dZ, parameters['W' + str(l+1)].T)
        dZ = dA * (cache['Z' + str(l)] > 0)  # ReLU derivative
        # The error was in the next line. We need to transpose X, not dZ
        gradients['dW' + str(l)] = np.dot(cache['A' + str(l-1)].T, dZ) / m
        gradients['db' + str(l)] = np.sum(dZ, axis=0, keepdims=True) / m
    return gradients
# 6. Update parameters
def update_parameters(parameters, gradients, learning_rate=0.01):
    L = len(parameters) // 2
    for l in range(1, L+1):
        parameters['W' + str(l)] -= learning_rate * gradients['dW' + str(l)]
        parameters['b' + str(l)] -= learning_rate * gradients['db' + str(l)]
    return parameters
# 7. Train the MLP model
def train_model(X, Y, layer_sizes, learning_rate=0.01, epochs=1000):
    parameters = initialize_parameters(layer_sizes)
    for i in range(epochs):
        # Forward pass
        A, cache = forward(X, parameters)
        # Compute loss
        loss = compute_loss(Y, A)
        # Backward pass
        gradients = backward(X, Y, parameters, cache)
        # Update parameters
        parameters = update_parameters(parameters, gradients, learning_rate)
        if i % 100 == 0:
            print(f'Epoch {i}: Loss = {loss}')
    return parameters
# 8. Display the weights of each layer
def display_weights(parameters):
    L = len(parameters) // 2
    for l in range(1, L+1):
        print(f'Layer {l} weights (W{l}):\n{parameters["W" + str(l)]}\n')
# 9. Example usage
if __name__ == "__main__":
    # Generate synthetic data
    X, Y = generate_data()
    # Define the architecture
    layer_sizes = [3, 5, 4, 1]  # 3 input features, 5 in hidden layer 1, 4 in hidden layer 2, 1 output
    # Train the model
    parameters = train_model(X, Y, layer_sizes, learning_rate=0.01, epochs=1000)
    # Display the weights
    display_weights(parameters)


Epoch 0: Loss = 3.223619121941664
Epoch 100: Loss = 3.223619121941664
Epoch 200: Loss = 3.223619121941664
Epoch 300: Loss = 3.223619121941664
Epoch 400: Loss = 3.223619121941664
Epoch 500: Loss = 3.223619121941664
Epoch 600: Loss = 3.223619121941664
Epoch 700: Loss = 3.223619121941664
Epoch 800: Loss = 3.223619121941664
Epoch 900: Loss = 3.223619121941664
Layer 1 weights (W1):
[[ 0.01059936  0.00617006  0.00683569 -0.01365956  0.01211944]
 [ 0.00261251 -0.00369277  0.00143388 -0.01776235  0.00408653]
 [-0.01029372 -0.0135267  -0.01522359  0.01112688 -0.00629263]]

Layer 2 weights (W2):
[[ 0.01533728 -0.00535801 -0.01707358 -0.01116524]
 [ 0.01235812 -0.00155898 -0.00548287  0.00160018]
 [ 0.00501783  0.01117399  0.01448499 -0.00359769]
 [-0.01326048 -0.00413465  0.00260281 -0.00963759]
 [-0.00957151  0.00343788 -0.00048652  0.00032797]]

Layer 3 weights (W3):
[[-0.00758495]
 [-0.00230401]
 [-0.00924233]
 [ 0.00890198]]

