In [ ]:
import numpy as np

class Perceptron:
    def __init__(self, input_dim, output_dim):
        # Initialize weights and biases with small random numbers
        self.weights = np.random.rand(input_dim, output_dim)
        self.biases = np.random.rand(output_dim)

    def forward(self, x):
        # Compute the weighted sum (dot product) + biases
        return np.dot(x, self.weights) + self.biases

if __name__ == "__main__":
    # Define dimensions
    input_dim = 10  # 10-dimensional input
    output_dim = 4  # 4 classes

    # Create the Perceptron model
    model = Perceptron(input_dim, output_dim)

    # Print the weights and biases
    print("Weights:\n", model.weights)
    print("Biases:\n", model.biases)


Weights:
 [[0.36374888 0.78693396 0.09860513 0.994099  ]
 [0.77276428 0.25020595 0.293068   0.29951896]
 [0.19673218 0.8801598  0.17534082 0.20848323]
 [0.97652462 0.04021597 0.45066903 0.67568807]
 [0.32705924 0.06073069 0.48866919 0.52882   ]
 [0.45612968 0.96494585 0.22448164 0.12358223]
 [0.69540942 0.2418801  0.17986551 0.71292555]
 [0.00384178 0.22550784 0.43283492 0.44182561]
 [0.65353244 0.91060769 0.28128708 0.98813218]
 [0.15928405 0.84988021 0.80195709 0.19158605]]
Biases:
 [0.81833184 0.90191215 0.42534678 0.09871125]


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

# Load the dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"
column_names = [f'feature_{i}' for i in range(1, 58)] + ['label']  # 57 features + 1 label
data = pd.read_csv(url, header=None, names=column_names)

# Separate features and labels
X = data.drop('label', axis=1)
y = data['label']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Normalize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize and train the model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Make predictions and evaluate the model
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# Output the model weights and biases
print("Model Weights:\n", model.coef_)
print("Model Bias (Intercept):\n", model.intercept_)

if __name__ == "__main__":
    pass


Accuracy: 0.9225199131064447
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.96      0.93       804
           1       0.93      0.88      0.90       577

    accuracy                           0.92      1381
   macro avg       0.92      0.92      0.92      1381
weighted avg       0.92      0.92      0.92      1381

Model Weights:
 [[-6.30484991e-02 -1.55966326e-01  5.37660271e-02  8.35457212e-01
   3.92067019e-01  1.25056243e-01  8.22607753e-01  1.76094406e-01
   2.76446896e-01  4.26478684e-02 -7.95107223e-02 -8.82724356e-02
   3.74448680e-03  5.07602317e-02  3.80416999e-01  9.06563815e-01
   4.46244506e-01  5.95168250e-02  1.88961167e-01  5.77098195e-01
   2.99528950e-01  2.79711781e-01  8.79688578e-01  1.48830897e-01
  -2.60683756e+00 -8.47713857e-01 -4.13631064e+00  2.06264349e-01
  -8.98191292e-01 -3.14601187e-01 -1.74403616e-01 -4.41755944e-01
  -6.41467780e-01  5.95893169e-02 -7.69932449e-01  4.25838667e-01
  -1.06913